services:
  front:
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=cp_user
      - DB_PASSWORD=pass
      - DB_NAME=bdd
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=bdd
      - MYSQL_USER=cp_user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql-cp-data:/var/lib/mysql
      - ./cp.sql:/docker-entrypoint-initdb.d/cp.sql

volumes:
  mysql-cp-data: