version: '3'
services:
  front:
    build: ./php
    image: anthonymasset/cp-php:latest
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: --init-file /docker-entrypoint-initdb.d/cp.sql
volumes:
  db_data: