services:
  front:
    platform: linux/amd64
    build: ./php
    ports:
      - 8085:80
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  db:
    platform: linux/amd64
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
    volumes:
      - mysql-cp-data:/var/lib/mysql

volumes:
  mysql-cp-data: